### ISSUE TITLE
The required "userId" or "username" param provided does not match any users 

### ISSUE THREAD

**Issue by rpelletierrefocus** [Zimbra-Community/zimbra-rocket#9]
Everything seems to be setup properly, but I am getting this error when I try to login.

```
API ➔ debug post users.createToken threw an error: Error: The required "userId" or "username" param provided does not match any users [error-invalid-user]


    at Object._getUserFromParams [as getUserFromParams] (app/api/server/helpers/getUserFromParams.js:23:9)


    at Object.post (app/api/server/v1/users.js:475:21)


    at app/api/server/api.js:343:82


    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)


    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:343:39)


    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)


    at packages/nimble_restivus/lib/route.coffee:59:33


    at packages/simple_json-routes.js:98:9


API ➔ debug Failure {


  statusCode: 400,




{


    success: false,


    error: 'The required "userId" or "username" param provided does not match any users [error-invalid-user]',


    stack: undefined,


    errorType: 'error-invalid-user'


  }


}


API ➔ debug POST: /api/v1/login


API ➔ debug POST: /api/v1/login
```

**Comment by rpelletierrefocus** [comment]
It should be noted that when I have userCreation turned off, but when I have it turned on, it says the user already exists. ??

**Comment by rpelletierrefocus** [comment]
I took another look at the documentation and was able to figure it out. It was passing the username jsmith.domain.com, when I had already created a user called jsmith with the same email.
